package net.lldp.checksims.parse.ast;

import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.stream.Stream;

import net.lldp.checksims.parse.Percentable;
import net.lldp.checksims.parse.Real;
import static net.lldp.checksims.parse.ast.Monad.unwrap;
import static net.lldp.checksims.parse.ast.Monad.wrap;

public class AST implements Percentable
{
    private final String tag;
    private final Set<AST> asts;
    private final Set<Integer> hashes;
    private final Integer hashCode;
    private final Map<Integer, AST> fingerprints;
    
    // scoring heuristics?
    private final Integer size;
    private final Integer depth;
    
    public AST(String tag, AST ... children)
    {
        this(tag, Arrays.asList(children).stream());
    }
    
    public AST(String tag, Stream<AST> children)
    {
        this.tag = tag;
        this.asts = new HashSet<>();
        this.hashes = new HashSet<>();
        this.fingerprints = new HashMap<>();
        
        Monad<Integer> size = wrap(0);
        Monad<Integer> depth = wrap(0);
        
        children.forEach(A -> {
            asts.add(A);
            hashes.add(A.hashCode());
            size.set(unwrap(size) + A.size);
            depth.set(A.depth > unwrap(depth) ? A.depth: unwrap(depth));
        });
        
        this.size = unwrap(size)+1;
        this.depth = unwrap(depth)+1;
        hashCode = _hashCode();
        
        fingerprint(wrap(fingerprints));
    }
    
    public Map<Integer, AST> getFingerprints()
    {
        return fingerprints; // Ideally should be immutable, but this kicks the GC in the ass
    }
    
    public void fingerprint(final Monad<Map<Integer, AST>> fpdb)
    {
        unwrap(fpdb).put(hashCode(), this);
        asts.stream().forEach(A -> A.fingerprint(fpdb));
    }
    
    public Real getPercentMatched(Map<Integer, AST> fpdb)
    {
        Real result = null;
        if (equals(fpdb.get(hashCode())))
        {
            result = new Real(size, size);
        }
        else
        {
            result = new Real(0, size);
        }
        
        for(AST t : asts)
        {
            result = result.scoreSummation(t.getPercentMatched(fpdb));
        }
        
        return result;
    }



    /*
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode()
    {
        return hashCode;
    }
    
    /*
     * AUTO GENERATED BY ECLIPSE
     * @see java.lang.Object#hashCode()
     */
    private int _hashCode()
    {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((hashes == null) ? 0 : hashes.hashCode());
        result = prime * result + ((tag == null) ? 0 : tag.hashCode());
        return result;
    }

    /*
     * AUTO GENERATED BY ECLIPSE
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj)
    {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        AST other = (AST) obj;
        if (hashes == null)
        {
            if (other.hashes != null)
                return false;
        } else if (!hashes.equals(other.hashes))
            return false;
        if (tag == null)
        {
            if (other.tag != null)
                return false;
        } else if (!tag.equals(other.tag))
            return false;
        return true;
    }

    @Override
    public Real getPercentageMatched()
    {
        throw new RuntimeException("cannot evaluate getPercentMatched()");
    }

    public Collection<? extends AST> getASTs()
    {
        return Collections.unmodifiableSet(asts);
    }
}
